services:
  - type: web
    name: simiyu-payload
    runtime: python
    plan: free
    region: frankfurt
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --worker-tmp-dir /dev/shm
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: PORT
        value: 5000
    healthCheckPath: /health
    autoDeploy: true
    persistentDisk:
      sizeGB: 1
      mountPath: /data
